### ISSUE TITLE
Bug difficult to explain :/

### ISSUE THREAD

**Issue by hadrienl** [justjohn/twig.js#68] opened 2013-03-15 09:42 UTC
Hi,

I updated to last tag recently to get the bugfix you made for me a month ago, and it added a new bug very difficult to isolate. The bug has been introduced by the commit 99d343f8f8005eb295c01ab1f7c5bead95568f44 ("#46 set parent context in nested for loops correctly").

I'll give you all that I can to reproduce it, and I hope you'll find it. Meanwhile, we keep to the 0.4.5 tag.

This is the data we give to twig.js compilator : https://gist.github.com/hadrienl/adb88760ada9ad4285a2

This is the twig code to be compiled : https://gist.github.com/hadrienl/cfaf5e1cb64260174ba3

The first loop is ok, but the second is not. Posts returns an array of Data.__Posts items such as Blog.Posts. But in the second case, Post are arrays instead of objects : https://dl.dropbox.com/u/8352589/Scrinechoutes/Capture%20d%E2%80%99%C3%A9cran%202013-03-15%20%C3%A0%2010.41.47.png

**Comment by evgenius** [comment] 2015-03-29 13:15
The example uses YUI. I included it but got issues with undefined Y.each, Y.clone and such.
So I can't reproduce it.
Hopefully it's fixed after two years :)
Closing it now.

**Closed by evgenius** 2015-03-29 13:15 UTC
